version: '3'

services:

  app:
    container_name: events_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: 8080
      DB_CONN: "postgres://postgres:kudabesi@docker.for.mac.localhost:5433/indosandb"
    volumes:
      - .:/app